package config

const version = "1.0"

var defaultConfig = `
siteTitle: backendboilerplate
sshKey: ~/.ssh/gitkey
PORT: 
  dev: 8001
  prod: 8000
update: 86400
domain: api.backendboilerplate.com
scheme: https
documentation: true
contacts:
  support_email: 'brian@backendboilerplate.com'
copyright:
  startYear: 2022
  url: 'http://www.backendboilerplate.com'
  name: DAWASCOPE
analytics: ''
secret: ...
logo: 'https://cseco.co.ke/assets/images/logo.png'
tokenSecret: autoGeneratedReally
GITHUB_OAUTH_CLIENT_ID=your client Id here
GITHUB_OAUTH_CLIENT_SECRET=your client secret here
LINKEDIN_OAUTH_CLIENT_ID: ..
LINKEDIN_OAUTH_CLIENT_SECRET: ..
TWITTER_OAUTH_CLIENT_ID: ...
TWITTER_OAUTH_CLIENT_SECRET: ...
FB_OAUTH_CLIENT_ID: "..."
FB_OAUTH_CLIENT_SECRET: ... # https://developers.facebook.com/apps/8623091061099143/settings/basic/
database:
  dev:
    databaseType: mariadb
    database:
      force: false
      mysql:
          HOST: localhost
          USER: ''
          PASS: ''
          DBNAME: ''
      mariadb:
          HOST: localhost
          USER: ''
          PASS: ''
          DBNAME: ''
      postgres:
          HOST: localhost
          USER: ''
          PASS: ''
          DBNAME: ''
  prod:
    databaseType: mariadb
    database:
      force: false
      mysql:
          HOST: localhost
          USER: ''
          PASS: ''
          DBNAME: ''
      mariadb:
          HOST: localhost
          USER: ''
          PASS: ''
          DBNAME: ''
      postgres:
          HOST: localhost
          USER: ''
          PASS: ''
          DBNAME: ''
mailer:
  dev:
    host: 
    port: 587
    secure: true
    auth:
      user: ''
      pass: ''
  prod:
    host: 
    port: 587
    secure: true
    auth:
      user: ''
      pass: ''
        
service:
  prod:
    name: backendboilerplate
    displayname: "backendboilerplate API"
    description: "backendboilerplate backend server"
  dev:
    name: dawascopeDev
    displayname: "backendboilerplate API in Dev env"
    description: "backendboilerplate backend server in Dev env"
`
